name: Deploy to Hetzner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Hetzner VPS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma client
        run: npx prisma generate
        
      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: "file:./dev.db"
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Stop the application
            pm2 stop buzau-realestate || true
            
            # Backup database
            cp /var/www/buzau-realestate/prisma/dev.db /var/www/buzau-realestate/backups/backup-$(date +%Y%m%d-%H%M%S).db || true
            
            # Clean old deployment
            rm -rf /var/www/buzau-realestate-new
            
            # Create new deployment directory
            mkdir -p /var/www/buzau-realestate-new
            
      - name: Upload files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: ".next,public,package.json,package-lock.json,prisma,next.config.js"
          target: "/var/www/buzau-realestate-new"
          
      - name: Complete deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/buzau-realestate-new
            
            # Install production dependencies
            npm ci --production
            
            # Generate Prisma client for production
            npx prisma generate
            
            # Create ecosystem file for PM2
            cat > ecosystem.config.js << EOF
            module.exports = {
              apps: [{
                name: 'buzau-realestate',
                script: 'node_modules/next/dist/bin/next',
                args: 'start',
                env: {
                  NODE_ENV: 'production',
                  PORT: 3000,
                  DATABASE_URL: 'file:./prisma/dev.db',
                  NEXTAUTH_URL: '${{ secrets.NEXTAUTH_URL }}',
                  NEXTAUTH_SECRET: '${{ secrets.NEXTAUTH_SECRET }}'
                }
              }]
            }
            EOF
            
            # Copy database from old deployment
            if [ -f /var/www/buzau-realestate/prisma/dev.db ]; then
              cp /var/www/buzau-realestate/prisma/dev.db ./prisma/dev.db
            else
              # First deployment - create database and seed
              npx prisma db push
              npx tsx prisma/seed.ts
            fi
            
            # Switch deployments atomically
            cd /var/www
            mv buzau-realestate buzau-realestate-old || true
            mv buzau-realestate-new buzau-realestate
            
            # Start the application
            cd buzau-realestate
            pm2 startOrRestart ecosystem.config.js
            
            # Clean up old deployment
            rm -rf /var/www/buzau-realestate-old
            
            # Setup logrotate and keep only last 10 backups
            find /var/www/buzau-realestate/backups -name "backup-*.db" -mtime +10 -delete 2>/dev/null || true